version: '3'
services:
#   db:
#     image: postgres:10.5-alpine
#     restart: always
#     volumes:
#       - data-flaskapi:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: admin
#       POSTGRES_USER: admin

  web:
    container_name: flaskapi
    build: ./web
    image: flaskapi
    volumes:
      - ./web:/app
    ports:
      - "5000:5000"
    # depends_on:
    #   - db
#       - redis
#   redis:
#     image: redis
# volumes:
#   data-flaskapi:
#     external: true